/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.test;

import com.mycompany.utils.MyConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class GestionReservation extends javax.swing.JFrame {

    /**
     * Creates new form GestionReservation
     */
    MyConnection mc = MyConnection.getInstance();
   //Connecter conn=new Connecter();       
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model= new DefaultTableModel();
    public GestionReservation() {
        initComponents();
        model.addColumn("id");
        model.addColumn("chair_billet");
        model.addColumn("voyage_num");
        model.addColumn("terminal");
        model.addColumn("portail");
        model.addColumn("embarquement");
        model.addColumn("localisation_id");
        try {
        stm=mc.getCnx().createStatement();
        ResultSet res=stm.executeQuery("Select * from billet");
        while(res.next()){
        model.addRow(new Object[]{res.getString("id"),res.getString("chair_billet"),res.getString("voyage_num"),
    res.getString("terminal"),res.getString("portail"),res.getString("embarquement"),res.getString("localisation_id")});}
        }catch(Exception e){System.err.println(e);}

        TableBillet.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBillet = new javax.swing.JTable();
        texchair_billet = new java.awt.TextField();
        textvoyage_num = new java.awt.TextField();
        textterminal = new java.awt.TextField();
        textembarquement = new java.awt.TextField();
        textlocalisation = new java.awt.TextField();
        textportail = new java.awt.TextField();
        AjouterBillet = new javax.swing.JButton();
        ModifierBillet = new javax.swing.JButton();
        SupprimerBillet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(204, 204, 204));

        SidePanel.setBackground(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TableBillet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(TableBillet);

        texchair_billet.setText("chair_billet");
        texchair_billet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texchair_billetActionPerformed(evt);
            }
        });

        textvoyage_num.setText("voyage_num");

        textterminal.setText("terminal");

        textembarquement.setText("embarquement");

        textlocalisation.setText("localisation");

        textportail.setText("portail");

        AjouterBillet.setLabel("Ajouter");
        AjouterBillet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterBilletActionPerformed(evt);
            }
        });

        ModifierBillet.setText("Modifier");
        ModifierBillet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBilletActionPerformed(evt);
            }
        });

        SupprimerBillet.setText("Supprimer");
        SupprimerBillet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerBilletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texchair_billet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textvoyage_num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textterminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textembarquement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textlocalisation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textportail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(AjouterBillet)
                        .addGap(51, 51, 51)
                        .addComponent(ModifierBillet)
                        .addGap(59, 59, 59)
                        .addComponent(SupprimerBillet)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(texchair_billet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textvoyage_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textterminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textportail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textembarquement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textlocalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouterBillet)
                    .addComponent(ModifierBillet)
                    .addComponent(SupprimerBillet))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        texchair_billet.getAccessibleContext().setAccessibleName("chair_billet");
        textvoyage_num.getAccessibleContext().setAccessibleName("voyage_num");
        textterminal.getAccessibleContext().setAccessibleName("terminal");
        textembarquement.getAccessibleContext().setAccessibleName("embarquement");
        textlocalisation.getAccessibleContext().setAccessibleName("localisation");
        textportail.getAccessibleContext().setAccessibleName("portail");
        AjouterBillet.getAccessibleContext().setAccessibleName("AjouterBillet");
        ModifierBillet.getAccessibleContext().setAccessibleName("ModifierBillet");
        SupprimerBillet.getAccessibleContext().setAccessibleName("SupprimerBillet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texchair_billetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texchair_billetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texchair_billetActionPerformed

    private void ModifierBilletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBilletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierBilletActionPerformed

    private void AjouterBilletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBilletActionPerformed
        // TODO add your handling code here:
        String chair_billet = texchair_billet.getText();
        String voyage_num = textvoyage_num.getText();
        String terminal = textterminal.getText();
        String portail = textportail.getText();
        String embarquement = textembarquement.getText();
        String localisation = textlocalisation.getText();
        
       String requete="insert into billet(chair_billet,voyage_num,terminal,portail,embarquement,localisation_id)VALUES('" +chair_billet+"','"+voyage_num+"','"+terminal+"','"+portail+",'"+embarquement+"','"+localisation+"')"; 

        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null,"Billet bien ajoute");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_AjouterBilletActionPerformed

    private void SupprimerBilletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerBilletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupprimerBilletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterBillet;
    private javax.swing.JButton ModifierBillet;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton SupprimerBillet;
    private javax.swing.JTable TableBillet;
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField texchair_billet;
    private java.awt.TextField textembarquement;
    private java.awt.TextField textlocalisation;
    private java.awt.TextField textportail;
    private java.awt.TextField textterminal;
    private java.awt.TextField textvoyage_num;
    // End of variables declaration//GEN-END:variables
}
