package com.mycompany.tests;



import com.mycompany.utils.MyConnection;
import java.sql.* ;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */

public class gestionService extends javax.swing.JFrame {

    /**
     * Creates new form gestionService
     */
    
 MyConnection mc = new MyConnection();
   //Connecter conn=new Connecter();       
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model= new DefaultTableModel();
    
    
    
    public gestionService() {
        initComponents();
        //initcomponent

       
model.addColumn("id");
model.addColumn("description reclamation");
model.addColumn("etat reclamation");
model.addColumn("date reclam");

try {
stm=mc.getCnx().createStatement();
ResultSet res=stm.executeQuery("Select * from reclamation");
while(res.next()){
model.addRow(new Object[]{res.getString("id"),res.getString("description_reclamation"),res.getString("etat_reclamation"),
    res.getString("date_reclamation")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void deplace(int i){
        
        try{
            
            txtid.setText(model.getValueAt(i,0).toString());
            txtdescirption_reclamation.setText(model.getValueAt(i,1).toString());
            txtetat_reclamation.setText(model.getValueAt(i,2).toString());
            txtdate_reclamation.setText(model.getValueAt(i,3).toString());
            
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"erreur deplacement"+e.getLocalizedMessage());
            
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdate_reclamation = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtdescirption_reclamation = new javax.swing.JTextField();
        txtetat_reclamation = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ModifierReclamButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        actualiser = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("id :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("description reclamation :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("etat reclamation :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("date réclamation :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 22, 204, 361);

        txtdate_reclamation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdate_reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdate_reclamationActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate_reclamation);
        txtdate_reclamation.setBounds(290, 190, 120, 20);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(290, 40, 120, 21);

        txtdescirption_reclamation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdescirption_reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescirption_reclamationActionPerformed(evt);
            }
        });
        getContentPane().add(txtdescirption_reclamation);
        txtdescirption_reclamation.setBounds(290, 90, 120, 20);

        txtetat_reclamation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtetat_reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtetat_reclamationActionPerformed(evt);
            }
        });
        getContentPane().add(txtetat_reclamation);
        txtetat_reclamation.setBounds(290, 140, 120, 20);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Réclamer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 260, 100, 23);
        jButton2.getAccessibleContext().setAccessibleName("Réclamer");

        ModifierReclamButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ModifierReclamButton.setText("Modifer");
        ModifierReclamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierReclamButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifierReclamButton);
        ModifierReclamButton.setBounds(550, 260, 100, 23);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 60, 450, 160);

        actualiser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        actualiser.setText("Actualsier");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });
        getContentPane().add(actualiser);
        actualiser.setBounds(430, 260, 100, 23);
        actualiser.getAccessibleContext().setAccessibleName("actualis");

        supprimer.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        supprimer.setText("supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer);
        supprimer.setBounds(680, 260, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdate_reclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdate_reclamationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdate_reclamationActionPerformed

    private void txtdescirption_reclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescirption_reclamationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescirption_reclamationActionPerformed

    private void txtetat_reclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtetat_reclamationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtetat_reclamationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
     /*    String requete2 = "INSERT INTO reclamation (description_reclamation,etat_reclamation,date_reclamation) "
                 + "VALUES(?,?,?)";
        
        try {
           PreparedStatement pst = cnx2.prepareStatement(requete2);  //utilise pour les requete dynamique
           pst.setString(1, r.getDescription_reclamation());
           pst.setString(2, r.getEtat_reclamation());
           pst.setString(3, r.getDate_reclamation());
           
           pst.executeUpdate();
           
           System.out.println("votre reclam est ajoute");
        
        
        } catch (SQLException ex) {
             System.err.println(ex.getMessage());
        }
        
    }*/
     // String id=txtid.getText();
        String description_reclamation=txtdescirption_reclamation.getText();
        String etat_reclamation=txtetat_reclamation.getText();
        String date_reclamation=txtdate_reclamation.getText();
        //String requete="insert into reclamation(id,description_reclamation,etat_reclamation,date_reclamation)VALUES('" +id+"','"+description_reclamation+"','"+etat_reclamation+"','"+date_reclamation+"')";
       String requete="insert into reclamation(description_reclamation,etat_reclamation,date_reclamation)VALUES('"+description_reclamation+"','"+etat_reclamation+"','"+date_reclamation+"')";
        try{
            stm.executeUpdate(requete);
JOptionPane.showMessageDialog(null,"reclamation bien ajoute");


        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ModifierReclamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierReclamButtonActionPerformed
        // TODO add your handling code here:
        try { 
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                
                stm.executeUpdate("UPDATE reclamation SET description_reclamation='"+txtdescirption_reclamation.getText()+"',etat_reclamation='"+txtetat_reclamation.getText()
                       +"',date_reclamation='"+txtdate_reclamation.getText()+
                        "' WHERE id= "+txtid.getText());
              
               JOptionPane.showMessageDialog(null,"reclamation bien modifier");
            } 
        } catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de modifier !!!!!!!");
        System.err.println(e);}
    }//GEN-LAST:event_ModifierReclamButtonActionPerformed

      
    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        try {
stm=mc.getCnx().createStatement();
ResultSet res=stm.executeQuery("Select * from reclamation");
while(res.next()){
model.addRow(new Object[]{res.getString("id"),res.getString("description_reclamation"),res.getString("etat_reclamation"),
    res.getString("date_reclamation")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
  
      
    }//GEN-LAST:event_actualiserActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        // TODO add your handling code here:
        try{
            int i=tble.getSelectedRow();
            deplace(i);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,"erreur deplavcement"+e.getLocalizedMessage());
            
        }
    }//GEN-LAST:event_tbleMouseClicked

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
          try {
             if(JOptionPane.showConfirmDialog(null,"attention vous avez supprimer votre reclamation,est ce que tu et sure?"
                     ,"supprimer reclamation",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
         
            if(txtid.getText().length() != 0){
        stm.executeUpdate("Delete From reclamation where id = "+txtid.getText());
         JOptionPane.showMessageDialog(null,"reclamation supprime");
             }//ca est pour recharger la list des stagiaire
            else { JOptionPane.showMessageDialog(null,"veuillez remplire le champ id !");}
        
        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de supprimer \n"+e.getMessage());} 
       
    }//GEN-LAST:event_supprimerActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModifierReclamButton;
    private javax.swing.JButton actualiser;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tble;
    private javax.swing.JTextField txtdate_reclamation;
    private javax.swing.JTextField txtdescirption_reclamation;
    private javax.swing.JTextField txtetat_reclamation;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
